name: "Update Canvas"
description: "Update Canvas with grade and comment"
inputs:
  subcommand:
    description: "Select subcommand: submit_assignment or grade_submission"
    required: true
  grade:
    description: 'Submission grade'
    required: false
  comment:
    description: 'Submission comment'
    required: true
  course_id:
    required: true
    description: 'Canvas CourseID'
  assignment_id:
    required: true
    description: 'Canvas AssignmentID'
  student_id:
    required: true
    description: "Canvas student id"
  canvas_api_token:
    required: true
    description: 'Canvas API token'
  read_org_token:
    required: true
    description: 'GitHub API token'

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "subcommand: ${{ inputs.subcommand }}"
        echo "Notifying Canvas for assignment ${{  inputs.assignment_id  }}..."
        echo "course_ID: ${{ inputs.course_id }}"
        echo "assignment_id: ${{ inputs.assignment_id }}"
        echo "student_id: ${{ inputs.student_id }}"
        echo "grade: ${{ inputs.grade }}"
        echo "comment: ${{ inputs.comment }}"

    - name: Submit Assignment
      shell: bash
      if: ${{ inputs.subcommand == 'submit_assignment' }}
      run: |
        curl --location "https://bth.instructure.com/api/v1/courses/${{ inputs.course_id }}/assignments/${{ inputs.assignment_id }}/submissions" \
        --header "Content-Type: application/x-www-form-urlencoded" \
        --header "Authorization: Bearer ${{ inputs.canvas_api_token }}" \
        --data-urlencode "submission%5Bsubmission_type%5D=online_text_entry" \
        --data-urlencode "submission%5Bbody%5D=${{ inputs.comment }}" \
        --data-urlencode "submission%5Buser_id%5D=${{ inputs.student_id }}" \
        --fail-with-body

    - name: Set attempt variable
      shell: bash
      id: set_attempt
      if: ${{ inputs.subcommand == 'grade_submission' }}
      run: |
          response=$(curl --silent --location --request GET 'https://bth.instructure.com/api/v1/courses/${{ inputs.course_id }}/assignments/${{ inputs.assignment_id }}/submissions/${{ inputs.student_id }}' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --header 'Authorization: Bearer ${{ inputs.canvas_api_token }}' \
          --fail-with-body)

          attempt=$(echo "$response" | jq -r '.attempt')
          echo "Attempt value is: $attempt"
          echo "attempt=$attempt" >> $GITHUB_OUTPUT

    - name: Grade Submission
      shell: bash
      if: ${{ inputs.subcommand == 'grade_submission' }}
      run: |
          curl --location --request PUT "https://bth.instructure.com/api/v1/courses/${{ inputs.course_id }}/assignments/${{ inputs.assignment_id }}/submissions/${{ inputs.student_id }}" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --header "Authorization: Bearer ${{ inputs.canvas_api_token }}" \
          --data-urlencode "comment%5Btext_comment%5D=${{ inputs.comment }}" \
          --data-urlencode "comment%5Battempt%5D=${{ steps.set_attempt.outputs.attempt }}" \
          --data-urlencode "submission%5Bposted_grade%5D=${{ inputs.grade }}" \
          --fail-with-body

    - name: Remove "failing" label. Det gör inget om denna får error, ignorera
      if: success()
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ inputs.read_org_token }}
        labels: "Integration fail"
      continue-on-error: true

    - name: Add "failing" label
      if: failure()
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ inputs.read_org_token }}
        labels: "Integration fail"
