# https://taskfile.dev

version: '3'

silent: true

vars:
  UTILS_REPO_FILES: https://raw.githubusercontent.com/bth-python/utils/refs/heads/main/student-repo-files
  UTILS_TMP_FILES: /tmp/tmp-utils/student-repo-files

tasks:
  download-utils:
    desc: "Downloads the utils repo to /tmp/tmp-utils, https://github.com/bth-python/utils"
    internal: true
    cmds:
      - task: clear-utils
      - git clone --quiet https://github.com/bth-python/utils.git /tmp/tmp-utils



  clear-utils:
    desc: "Removes /tmp/tmp-utils, used to clear the utils repo"
    internal: true
    cmds:
      - rm -rf /tmp/tmp-utils



  download-tests:
    desc: "Replaces files in tests/ with files from the utils repository, https://github.com/bth-python/utils"
    cmds:
      - task: download-utils
      - cp -a {{.UTILS_TMP_FILES}}/tests/. tests
      - task: clear-utils
      - echo "Tests downloaded successfully."



  download-ruff-config:
    desc: "Downloads the ruff configuration file from the utils repository"
    cmds:
      - curl -L -o ruff.toml {{.UTILS_REPO_FILES}}/ruff.toml
      - echo "Ruff configuration downloaded successfully."



  download-taskfile:
    desc: "Downloads the Taskfile from the utils repository"
    cmds:
      - curl -L -o Taskfile.yml {{.UTILS_REPO_FILES}}/Taskfile.yml
      - echo "Taskfile downloaded successfully."



  download-lab:
    desc: "Download a lab"
    cmds:
      - python3 {{.CLI_ARGS | default "src/kmom01/lab1/lab.py"}}