name: PR Opened Handler

on:
  workflow_dispatch:

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Handling PR opened!"
      

1. Passing Structured Data (e.g., JSON) as Inputs
Suppose your decider workflow needs to pass a list of PR labels, files changed, or environment matrix to called workflows.

YAML
# main.yml
jobs:
  call-decider:
    uses: ./.github/workflows/decider.yml
    with:
      event_name: ${{ github.event_name }}
      pr_labels: ${{ toJson(github.event.pull_request.labels) }}
Then in decider.yml, you can parse this JSON input:

YAML
# decider.yml
on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
      pr_labels:
        required: false
        type: string

jobs:
  decide:
    runs-on: ubuntu-latest
    steps:
      - name: Parse PR labels
        run: |
          echo 'PR labels: ${{ inputs.pr_labels }}'
          echo '${{ fromJson(inputs.pr_labels) }}'
2. Passing Environment Variables or Secrets
You can pass secrets or environment variables through workflow_call inputs (but avoid secrets in plain text):

YAML
# main.yml
jobs:
  call-decider:
    uses: ./.github/workflows/decider.yml
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
And in decider.yml, use as environment:

YAML
jobs:
  decide:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: echo "Secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
3. Passing Conditional Data and Acting on It
For example, pass a flag or structured data and let the called workflow branch logic:

YAML
# main.yml
jobs:
  call-decider:
    uses: ./.github/workflows/decider.yml
    with:
      needs_deploy: ${{ github.ref == 'refs/heads/main' }}

# decider.yml
on:
  workflow_call:
    inputs:
      needs_deploy:
        type: boolean
        required: false

jobs:
  decide:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.needs_deploy == 'true' }}
        run: echo "Deploying..."
      - if: ${{ inputs.needs_deploy != 'true' }}
        run: echo "Not deploying."
4. Using repository_dispatch to Send Custom Payloads
You can trigger another workflow and send a custom payload with dynamic keys:

YAML
# In decider.yml
- name: Trigger another workflow
  run: |
    curl -X POST \
      -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
      -H "Accept: application/vnd.github+json" \
      https://api.github.com/repos/${{ github.repository }}/dispatches \
      -d '{"event_type":"custom-event","client_payload":{"foo":"bar","list":["a","b","c"],"user":"Andreas"}}'
The triggered workflow can then access this payload via github.event.client_payload.