name: Tester workflow

on:
  workflow_call:
    inputs:
      kmom_paths:
        required: true
        type: string

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      kmoms: ${{ steps.set-matrix.outputs.kmoms }}

    steps:
      - name: Extract kmom based on tag
        id: set-matrix
        run: |
          TAG="${GITHUB_REF#refs/tags/}"   # Remove refs/tags/
          NUM=$(echo "$TAG" | sed -E 's/^v([0-9]+).*/\1/')
          echo "First number after v: $NUM"
          PADDED=$(printf "%02d" "$NUM")
          echo "Result: $PADDED"
          KMOM="kmom$PADDED"


          KMOMS=$(echo '${{ inputs.kmom_paths }}' | jq -c --arg b "$KMOM" '.[$b].kmoms // []')

          echo "✅ Kmom: kmom$PADDED"

          echo "kmoms={\"folder\":$KMOMS}" >> $GITHUB_OUTPUT

  run-kmoms:
    needs: [generate-matrix]
    if: needs.generate-matrix.outputs.kmoms != '{"folder":[]}'
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.kmoms) }}

    steps:
      - name: setup-python
        uses: bth-python/utils/.github/actions/setup-python@main

      - name: "Validate code"
        run: uv run ruff check $(echo "${{ matrix.folder }}" | sed 's/tests/src/')

      - name: Run kmom test in ${{ matrix.folder }}
        run: |
          echo "🔬 Running kmom: ${{ matrix.folder }}"
          uv run tester -f ${{ matrix.folder }}

      - name: Run extra tests in ${{ matrix.folder }}
        continue-on-error: true
        run: |
          echo "🔬 Running extras: ${{ matrix.folder }}. It is OK if these tests fail. It will not affect your grade"
          uv run tester -f -e ${{ matrix.folder }}
